### ISSUE TITLE
Make axis clearing optional

### ISSUE THREAD

**Issue by mohammed-hababeh** [kanishkegb/pyplot-3d#1]
I have the following use-case: I am plotting multiple drones in the same axis. And because the the first line in the draw_at method of the uav class is to clear the axis, I am not able to do it. It would be nice to have this as an option rather than doing it all the time. 

Somehting like 

`
def draw_at(self, x=np.array([0.0, 0.0, 0.0]).T, R=np.eye(3), clear_axis=True):
    if clear_axis:
        self.ax.clear()
`

I am not sure if you would like this as well. And I was in a hurry to use it so I did it in a forked version of your repository. I am happy to delete the forked version if you add this to the original repository. 

PS: thank you for the cool library.

**Comment by kanishkegb** [comment]
Thank you for the issue, and I am glad that you found it useful. Having a fork is totally fine, and that is the intended use of that. 

If you want to make a pull request from your fork, I am more than happy to accept that.

**Comment by mohammed-hababeh** [comment]
Thanks for the quick response. Maybe I will wait for the PR until I am done with the project in case I need to edit some more things. I will close the issue for now.
